### ISSUE TITLE
How to make?

### ISSUE THREAD

**Issue by t0mtee** [raulbojalil/cafiine-server-gui#1]
So, this may sound stupid, but I have NO idea how to make a program. can someone plase tell me how to soon? Thanks! 😄

**Comment by Arbifoxx** [comment]
Same here

**Comment by Arbifoxx** [comment]
Found Out!! Get visual studio, open the .sln, run the build, and then go to cafiine-server-gui/CafiineServerUI/bin/debug and Done!!
